### ISSUE TITLE
Ajax request failed with status: Unauthorized

### ISSUE THREAD

**Issue by tsqn** [ostreifel/wiql-editor#1]
Hi,
I have an error when i try to use link in result table.
![image2](https://cloud.githubusercontent.com/assets/20081583/22691247/22f4f15a-ed6c-11e6-9070-4a9e97f8c734.png)
![image](https://cloud.githubusercontent.com/assets/20081583/22691249/25197046-ed6c-11e6-955d-b596c47020df.png)

Can you help me with this problem?

**Comment by ostreifel** [comment]
Do you have access to workitem 1801 normally or is the url malformed? - Open a workitem and change the id in the url to 1801 to check. Also what do those error message say in english?

Is this on vsts or an onpremise installation of tfs, if so what version?

**Comment by tsqn** [comment]
Yes, i have access to this workitem .
In English error message is "Ajax request failed with status: Unauthorized."
Microsoft Visual Studio Team Foundation Version 14.102.25423.0
![2017_02_08_13_21_18_](https://cloud.githubusercontent.com/assets/20081583/22725881/99f8c344-ee02-11e6-9140-9014a4b39bc8.png)
![2017_02_08_13_28_05_](https://cloud.githubusercontent.com/assets/20081583/22725882/99fa3224-ee02-11e6-9d58-5fa219a62b5a.png)

**Comment by ostreifel** [comment]
[1.4.8](https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor) Fixed

**Comment by tsqn** [comment]
Thx for your fast response.
