### ISSUE TITLE
wiql is loading slowly and sometimes it is not loading from playground

### ISSUE THREAD

**Issue by rezoan** [ostreifel/wiql-editor#11]
In TFS 2015 OnPrem the wiql is loading slowly and sometimes it is not loading from playground after waiting long time.

Also the option to edit the existing queries from query tab is missing.

![image](https://user-images.githubusercontent.com/1701375/33658050-6beff4e6-daa5-11e7-9fec-da8753ee71d1.png)

![image](https://user-images.githubusercontent.com/1701375/33657962-299b42f8-daa5-11e7-868a-e256e0c25fef.png)

![image](https://user-images.githubusercontent.com/1701375/33659178-7b49eeac-daa9-11e7-8c61-bb1b80289dcf.png)

![image](https://user-images.githubusercontent.com/1701375/33659180-7beb7736-daa9-11e7-908a-6846f4656ea1.png)

**Comment by ostreifel** [comment]
What is the extension version and browser of this?

Also please send to ottost@microsoft.com the 2 [fiddler traces](https://www.telerik.com/fiddler/fiddlercap) for both loading the playground and loading the context menu that the edit existing query should be in.
