### ISSUE TITLE
Clicking the browser back button does not navigate back if I click Edit Wiql from a query's results view if you're using Chrome

### ISSUE THREAD

**Issue by MarkIannucci** [ostreifel/wiql-editor#13]
(My team and I are really thankful for your work, please take this issue as a bug report for functionality we deeply enjoy using).

Steps to reproduce:
1.)  From the Work Queries section in TFS, select a query on the left
2.)  Click the Edit Wiql button in the results section
3,)  That brings you to the Wiql Editor... 
4.)  Use your mouse's back button to navigate backwards

Expected result:
You go back to the query list and results page (perhaps with a warning asking if you want to save your changes)

Actual result:
The screen doesn't change.

**Comment by ostreifel** [comment]
Extensions do not have access to browser navigation events.

When I try your repro steps above I get navigated to the page I was on before the query results page.

I have added a keyboard command to the query editor to make keyboard exit easier.

F1=> 'exit' => enter
![image](https://user-images.githubusercontent.com/5203542/37379468-d38c6aa2-26f0-11e8-8770-e2cf95a288fd.png)
