### ISSUE TITLE
Query can not be saved

### ISSUE THREAD

**Issue by serafJ** [ostreifel/wiql-editor#15]
Hi,

save button is always disabled. If I try to save query using CTRL+S error message "ok callback not set" is displayed

Console log:
![image](https://user-images.githubusercontent.com/40264907/41406035-967ef2f0-6fcb-11e8-8b6f-f2260ffeee01.png)

Thank you for providing such amazing addon! Hopefully you will be able to fix this issue fast.

**Comment by ostreifel** [comment]
Fixed.

Thanks for the report.
