### ISSUE TITLE
AsOf will not allow @today - #

### ISSUE THREAD

**Issue by bechtner** [ostreifel/wiql-editor#16]
Using AsOf with the @today variable minus a number, e.g. "asof @today-7" returns:

Expecting end of string. The error is caused by <<-7>>.

**Comment by ostreifel** [comment]
This is a limitation of the wiql syntax not the extension but may be requested as a feature [here](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services)

The only way to specify asof today is in the format

```sql
SELECT
        [System.Id]
FROM workitems
ASOF '2018-01-31'
```

**Comment by bechtner** [comment]
Thank you for the fast response. I've filed a request on the VSTS site.
