### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by LoriAllen** [ostreifel/wiql-editor#17]
How do I grant permissions to Contributors to use Wiql Playground? (TFS 17 OnPrem)
They can see it, but it won't let them use it.

**Comment by ostreifel** [comment]
What kind of errors are they getting when they try to use it? Does the browser show anything in the devconsole (f12)?

**Comment by ostreifel** [comment]
When you say that they can not use it what are they unable to do? Does it give an error when it tries to load the page? Does it give it an error when they try to run a query in the playground? Does it give an error when they try to save a query?

**Comment by LoriAllen** [comment]
Hi Otto,
I appreciate your offers to help. It works for me, but for another developer he gets a permission denied error. He’s the one that asked me to install it, but he found a work around. How do I go about un-installing it? I’m new to TFS (on prem) administration.
-Lori

**Comment by ostreifel** [comment]
Top right from homepage of your collection
![image](https://user-images.githubusercontent.com/5203542/43931924-02af0f40-9bf6-11e8-9d27-f61587b54398.png)

This will then show a list of extensions look for the wiql editor icon, click the ... and click uninstall
![image](https://user-images.githubusercontent.com/5203542/43931958-3caeff20-9bf6-11e8-8a77-cbea4521be56.png)
