### ISSUE TITLE
Enhanced Query Export is no longer including all of the fields from the query - eg. Description

### ISSUE THREAD

**Issue by mstrippelhoff** [ostreifel/wiql-editor#19]
We've been using Enhanced Query Export for months without any issues. It's no longer including all of the fields from the Queries.

**Comment by ostreifel** [comment]
I think you are in the wrong place this is for the wiql editor not the [Enhanced Export](https://marketplace.visualstudio.com/items?itemName=mskold.mskold-enhanced-export) extension.
