### ISSUE TITLE
Error Saving Query - Unable to get property 'html' of undefined or null reference

### ISSUE THREAD

**Issue by yayitserica** [ostreifel/wiql-editor#21]
![image](https://user-images.githubusercontent.com/15487798/48647557-313eb600-e9a1-11e8-8e1d-67773e9e377b.png)

Can you clarify why I am receiving this error?

I get a different error when using Chrome:

![image](https://user-images.githubusercontent.com/15487798/48647722-af02c180-e9a1-11e8-82ea-d474dfce0d46.png)

**Comment by ostreifel** [comment]
Added a null check to the lines that used an html property. Root cause is probably mismatch in what is returned from different versions of tfs. 

Please verify that this fixes for you

**Comment by yayitserica** [comment]
Thanks @ostreifel .  I don't see the HTML error on my end but checking in with my colleague to make sure he isn't experiencing it.  Will follow up if this error persists.
