### ISSUE TITLE
Filter by date and  time (hour)

### ISSUE THREAD

**Issue by bathiyasri2** [ostreifel/wiql-editor#24]
There should be possibility to filter  by "changed date and time" in Wiql. Even better if you can this feature in default query section. Basically i want to query work items which changed during last 'x' hours. 

in wiql - 

System.ChangedDate ='12/07/2018, 6:42:45' or System.ChangedDate =('12/07/2018, 6:42:45')-1hour

**Comment by ostreifel** [comment]
There is a flag [(```timePrecision```)](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query%20by%20wiql?view=azure-devops-rest-4.1#uri-parameters) that I could expose that would allow you to do this in the playground but it would not be work if you tried to save the query or open in it the in product queries menu and so I think making it available in the playground would create more problems than it would solve.

As a workaround you can apply decimal offsets to the @today macro as long as you can express your query in terms of that macro.

Here is an example of that.
![image](https://user-images.githubusercontent.com/5203542/49633711-3e066680-f9af-11e8-8bea-8eb65c4f6f04.png)
![image](https://user-images.githubusercontent.com/5203542/49633731-51193680-f9af-11e8-8eaf-9f4afcb7eddb.png)
