### ISSUE TITLE
Wiql results provided via API doesn't match results in Azure devops web gui 

### ISSUE THREAD

**Issue by grabmana** [ostreifel/wiql-editor#26]
Calling Wiql endpoint via Azure devops REST API "WIQL query by ID" provides only work items' ids and links to the workitem, but not columns defined in the query itself.
Doing the same in web interface provides columns specified in the query.

**Comment by CCargan** [comment]
The API follows the described rules in the Important box here: https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#asof-historical-queries
