### ISSUE TITLE
Saved changes does not get applied in "Results" nor "Editor" view.

### ISSUE THREAD

**Issue by v-jaruck** [ostreifel/wiql-editor#28]
1) open existing query which is saved in "My queries" in "Editor" view
2) open "..." > "Edit query wiql" 
3) edit query displayed as text (no error shown) 
4) "Save query" button appears active > click it > two issues in console:
![image](https://user-images.githubusercontent.com/39310989/59677926-64f9ec80-91cb-11e9-8d24-2e075a46309e.png)
5) close wiql editor with "x"
6) no change in my query present (even if I force reload), also the modification will not be present if I open the wiql editor again

thanks, Jan

**Comment by v-jaruck** [comment]
if anyone struggles with this like I do, here is a workaround:
"Wiql Playground" > build query > "Open in queries"

**Comment by jhoak** [comment]
+1, frustrating that such a simple workflow fails with no indication of what's happened. I can't even find my saved query...
