### ISSUE TITLE
Adding an additional field to WIQL removes resulting columns

### ISSUE THREAD

**Issue by jamiemaclennan** [ostreifel/wiql-editor#29]
Execute this query in Wiql Playground

> SELECT
        [System.Id],
        [System.WorkItemType],
        [System.Title],
        [System.State],
        [System.AreaPath],
        [System.AreaLevel1],
        [System.AreaLevel2],
        [System.RelatedLinkCount],
        [System.IterationPath]
FROM workitems
WHERE
        [System.TeamProject] = @project
        AND [System.WorkItemType] = 'Epic'
        AND [System.RelatedLinkCount] > 1
ORDER BY [System.ChangedDate] DESC

And you get all the columns.  Add [System.History] to the projection and the ID, AreaLevel1, AreaLevel2, and RelatedLinkCount fields magically disappear!

**Comment by ostreifel** [comment]
This looks like a wiql issue rather than an issue with the extension

Pinging @mmanela
