### ISSUE TITLE
Unable to Save Query

### ISSUE THREAD

**Issue by EisenbergEffect** [ostreifel/wiql-editor#3]
Whenever I open up the query editor and paste in a new query, then save, the query is not saved. I've tried this repeatedly, with different queries and after refreshing the browser. I'm using Safari on a Mac. This worked fine a few weeks ago.

**Comment by ostreifel** [comment]
Updated [1.4.17](https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor)
