### ISSUE TITLE
Enable TimePrecision 

### ISSUE THREAD

**Issue by mercury77** [ostreifel/wiql-editor#30]
using REST API this query works 
/POST https://****/****/***/_apis/wit/wiql?timePrecision=true&api-version=5.0
{
"query": "SELECT [System.ID], 
[System.Title], [System.State],[System.CreatedDate] FROM WorkItems WHERE [System.TeamProject]='MyProject' AND [System.CreatedDate] = '2019-06-20T08:51:14.863Z'"
}
in WIQL the same query fail because timePrecision is not enable by default
At the moment you can compare 2 Date but not 2 DateTime

**Comment by ghittab** [comment]
@ostreifel 
In playground.ts can you put "true" in the function queryByWiql(), so you can enable the timePrecision parameter?
LOC: https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/wiqlPlayground/playground.ts#L54
