### ISSUE TITLE
WIQL query only returns first 50 rows of results

### ISSUE THREAD

**Issue by prodons** [ostreifel/wiql-editor#32]
**Describe the bug**
Have created a query using WIQL Playground but the results appear to be limited to the first 50 rows.
Message at foot of report "Showing first 50 results" without any obvious sign/link to show additional results.
When we click "Open in queries" CTA then the vsts UI displays 100 results.
We need to use WIQL because the asof functionality isn't available in vsts.

**Environment:**
 - Chrome
 - Hosted

**Screenshots**
No errors in the dev console - returns 200 response

**Expected behavior**
I expect to see all work items that match the query to be displayed when I press "Run"

**Additional context**
N/A

**Comment by ostreifel** [comment]
In order to limit the scope of the extension the playground was intentionally written to be a very limited environment for testing queries. 

If you use the open in queries and save as a new query the saved query should still be using the asof clause.

**Comment by prodons** [comment]
Thanks for confirming Otto
