### ISSUE TITLE
WIQL supports EVER operator but unable to save to VSTS as a custom query

### ISSUE THREAD

**Issue by prodons** [ostreifel/wiql-editor#33]
**Describe the bug**
I've been using the EVER operator against [system.iteration.path] to allow us to track work items that have spilled over to another sprint. 

I'm able to get the results in WIQL which has been great even though there is a red warning icon displayed at the start of the line.

When I select "Open in queries", the results are displayed in VSTS but I'm unable to save the query. I get a message "The operator for row 3 is not recognized". 

In editor view I can see that the WAS EVER operator has a red exclamation mark. I'd really appreciate any advice you have as we use dynamic queries quite often.

Here's a snippet of my query with the project/team replaced with generic terms:

SELECT
        [System.Id],
        [System.WorkItemType],
        [System.Title],
        [System.State],
        [Microsoft.VSTS.Scheduling.StoryPoints],
        [System.AreaPath],
        [System.IterationPath]
FROM workitems
WHERE
        [System.TeamProject] = @project
        AND [System.WorkItemType] = 'User story'
        AND [System.AreaPath] IN ('project\team')
        **AND [System.IterationPath] EVER @CurrentIteration('[project]\team') -1**
        AND [System.IterationPath] = @currentiteration('[project]\team')
ORDER BY [System.Id] ASC
ASOF '12/03/19 17:00'

**Environment:**
- Chrome
 - Azure Dev Ops

**Screenshots**

**To Reproduce**
See above

**Expected behavior**
Custom query can be saved in VSTS

**Additional context**
N/A

**Comment by ostreifel** [comment]
Create a new query and use the extension's edit option to paste and save the wiql.
![image](https://user-images.githubusercontent.com/5203542/70129321-601edd00-1633-11ea-9b80-b885d7a18b00.png)
