### ISSUE TITLE
Don't see the WIQL Editor tab

### ISSUE THREAD

**Issue by spam2ignore** [ostreifel/wiql-editor#42]
So this will almost certainly make me look stupid, but, that's fine.

I'm in Azure Devops, but when I go to the boards and then create a query, I don't see the WIQL Editor tab anywhere. I'm sure I'm missing something obvious, but my question is, what am I missing? The ADO native editor sucks, and I really need the ability to write WIQL queries.

Thanks!

**Comment by ostreifel** [comment]
![image](https://user-images.githubusercontent.com/5203542/78416225-58207b00-75dc-11ea-944c-783aacd43566.png)

**Comment by spam2ignore** [comment]
@ostreifel, thanks. I'd actually already checked out the More commands menu and didn't see it there, so my guess is that the person who told me that they'd installed the extension actually has not.

Thank you again, closing this "issue."

**Comment by spam2ignore** [comment]
@ostreifel, thank you. I'd actually checked in the More commands menu and didn't see it listed there, so I'm guessing that the real issue is that the person who told me that they'd installed the extension didn't.

Thank you again, closing this "issue."

**Comment by spam2ignore** [comment]
@ostreifel, thank you. I'd actually checked the More commands menu and didn't see it there (should have called that out in my original post). I'm guessing that the actual issue is that the person who told me that they'd installed the extension actually hasn't.

Thank you again.

**Comment by spam2ignore** [comment]
@ostreifel, thanks. I'd actually already checked out the More commands menu and didn't see it there, so my guess is that the person who told me that they'd installed the extension actually has not.

Thank you again, closing this "issue."
