### ISSUE TITLE
Query Across Projects Stopped Working

### ISSUE THREAD

**Issue by maspbury** [ostreifel/wiql-editor#47]
**Describe the bug**
Query Across Projects Stopped Working

**Environment:**
 - Chrome
 - hosted (Azure Devops)

**Screenshots**
![image](https://user-images.githubusercontent.com/67329785/85419494-c61f7300-b537-11ea-923b-785ce57210fc.png)

**To Reproduce**
Data should be returned from other projects. This stopped working last week but then it started working again even though I made no changes to the query.

**Expected behavior**
I  expect results from multiple projects.

**Additional context**

**Comment by ostreifel** [comment]
This looks like a bug in Azure Boards rather than the wiql editor extension.

![image](https://user-images.githubusercontent.com/5203542/85485033-cf7efe80-b57c-11ea-9f7c-e9f02efc0fdb.png)
