### ISSUE TITLE
WIQL ASOF does ignore System.Tags filter

### ISSUE THREAD

**Issue by frankroghair** [ostreifel/wiql-editor#50]
**Issue**:
[microsoft.zip](https://github.com/ostreifel/wiql-editor/files/5595174/microsoft.zip)

My Query:
SELECT
    [System.Id],
    [System.WorkItemType],
    [System.Title],
    [System.AssignedTo],
    [System.State],
    [System.Tags]
FROM workitems
WHERE
    [System.TeamProject] = @project
    AND NOT [System.Tags] CONTAINS 'MyTag'
ASOF '2020/7/23'

Result in list of work items including work items with Tags  'MyTag'
See attached screenshots

I am able to reproduce this on 18.170.30525.1 (Azure DevOps Server 2020)
For adding the ASOF part of the query the following extension is used : https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor

Hopefully you can help in resolving this issue.
Thanks in advance.

**Answer microsoft**:
I have checked and concluding you that the ASOF parameter doesn’t work as expected in Azure DevOps 2019 and 2020 respectively.
Also, upon checking with internal team, they mentioned that we don’t own the Wiql Editor extension- https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor#qna 

We would like you to reach out to respective extension provider by creating an issue on Issues · ostreifel/wiql-editor · GitHub
You would get the right team engagement who can help you addressing this. 

As we are from Azure DevOps team, we couldn’t provide much help here. I am sorry about that 

Should you have any questions feel free to write to me.

**Comment by ostreifel** [comment]
The extension only provides ui for hitting the api provided by azure devops. The actual execution of the query is done by azure devops.
