### ISSUE TITLE
Extension is not working correctly on DevOps 2020 On-Prem Environment

### ISSUE THREAD

**Issue by ghost** [ostreifel/wiql-editor#53]
I'm trying to use the extension of DevOps 2020 On-Prem Environment but every time I try to run the extension I receive the error below:

An undefined error occurred while attempting to connect to the server. Status code 0: .

Server Version is Version Dev18.M170.6
Client is Edge - Version 87.0.664.66 (Official build) (64-bit)

**Comment by frankroghair** [comment]
I have the same issue, is there a fix available ?
