### ISSUE TITLE
Save button doesn't work on replatformed query page

### ISSUE THREAD

**Issue by milemons** [ostreifel/wiql-editor#59]
**Describe the bug**
When the new preview is turned on (turn on preview "New Boards Hubs"), there is an issue saving the query. Somehow the callback argument is lost

**Environment:**
 - Browser [e.g. chrome, edge]: Crhome
 - onpremises (Azure Devops Server/tfs) or hosted (Azure Devops): Both

**Screenshots**
![image](https://user-images.githubusercontent.com/58820510/145625100-9ba56626-5f67-4a24-adb0-25df4761f006.png)

**To Reproduce**
1. Go to a queries page that has the extension installed
2. Turn on New Boards Hub preview in the preview panel
2. Click on the header ... to select "Edit WIQL" extension
3. Click "Save Query" in the wiql editor

**Expected behavior**
The query should save properly

**Additional context**
n/a

**Comment by ostreifel** [comment]
I tried to repro this but when I enable the "New boards Hubs" slider the queries page doesn't load anymore.

**Comment by milemons** [comment]
We have released a fix for that issue & it is slowly rolling out. In the meantime, you can get around it by turning off bundling (can provide steps in the morning)

**Comment by milemons** [comment]
Steps to turn off bundling:
1. Go to azure devops project you would like to test on
2. Open up chrome dev tools
3. Go to the console and copy/paste `document.cookie="TFS-BUNDLING=disabled"`. Hit enter
4. Reload the page - you should see a black bar at the bottom of the page
5. Click on "Settings" in the bottom right
6. Disable bundling / verify bundling is disabled
7. Queries page should load

**Comment by ostreifel** [comment]
It looks like the proxy logic that the extension is relying upon is removing data that the extension is trying to pass through.

![image](https://user-images.githubusercontent.com/5203542/145957414-4050d062-8429-4e6a-ad81-280e08e21b74.png)
![image](https://user-images.githubusercontent.com/5203542/145957441-e02a0635-f00d-4f0f-9caf-24429a30ee8b.png)
Specifically this call [in the queryEditor](https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/queryEditor/queryEditor.ts#L64) is trying to pass a callback to the code that [manages the dialog state](https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/queryEditor/queryDialog.ts#L51) but the proxy logic for functions is removing the property that contains the callback.


![image](https://user-images.githubusercontent.com/5203542/145955955-15c432c4-00a1-4049-8ea9-7c5c5df94444.png)

Has there been a recent change in the sdk logic that handles the arguments passed to and from proxy functions that could be causing this regression?

**Comment by brunooflores** [comment]
Does anyone here know how to rollback to the old UI of azure?
@ostreifel are you using the new interface of Azure or the old one?
This issue has been started when I accepted the suggestion of platform to use the new UI.

**Comment by kasajian** [comment]
@milemons @ostreifel 
Curious if there's any plans to fix this.

**Comment by kasajian** [comment]
Is there any other way to set the wiql of an existing query?   I could do it from the command line, or via rest / curl -- then at least the query can be run from the UI.

**Comment by mathiash98** [comment]
This is still an issue 🤔 
![image](https://github.com/ostreifel/wiql-editor/assets/5204006/24e75070-c676-4679-8a1a-a22b1875688c)

**Comment by AdrienViala** [comment]
still opened : 
![image](https://github.com/ostreifel/wiql-editor/assets/39263057/c371d565-48da-4890-ad65-0153ce275b9e)

**Comment by mvonballmo-uster** [comment]
I'm still getting this error as of today. I have the latest version (2.0.97) installed.

I briefly tried the suggestion above for disabling bundling, but the resulting UI was much, much slower. Also, I still got the same error message.

Edit: The issue is definitely related to the "New Boards Hubs" preview feature. When I turned it off, I could once again save queries.

![image](https://github.com/ostreifel/wiql-editor/assets/162302979/52d97cdc-c510-483b-a86c-acbb98667597)

Is there a workaround? Is there a fix coming?
