### ISSUE TITLE
Running WorkItemLinks queries returns results, does not populate table

### ISSUE THREAD

**Issue by Kujawadl** [ostreifel/wiql-editor#6]
## Description
**TFS Version:** TFS 2015 Update 3
**Extension Version:** 1.6.22

Running the following query:

```sql
SELECT [System.Id], [System.State], [System.WorkItemType] 
FROM WorkItemLinks 
WHERE
        [Source].[System.Id] = 107932
        AND [System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Forward'
        AND [Target].[System.WorkItemType] <> ''
ORDER BY [System.Id]
```

The only thing displayed in the results is: "Found {#} results" (but with an actual number). Screenshot attached.

## Debugging

I've also done my best to try and debug this a bit, though I don't know how helpful it will be, but here goes (keeping in mind I know almost nothing about React.js):

As best I can tell, React is having a problem rendering the rows that are created in `WorkItemRow.render()`, since the results table is empty:

```html
<div id="query-results">
  <div data-reactid=".1">
    <table data-reactid=".1.0">
      <tbody data-reactid=".1.0.0"></tbody>
    </table>
    <div data-reactid=".1.1">Found 11 results</div>
  </div>
</div>
```

I set breakpoints in the render function to try and capture the results of `return (React.createElement("a"...`. I put the first 5 or 6 row objects into an array, and used [CircularJSON](https://www.npmjs.com/package/circular-json) to stringify them. The resultant JSON is also attached. Maybe you can find something there that's out of the ordinary compared to a non-WorkItemLinks result.

## Attachments

[capture](https://cloud.githubusercontent.com/assets/14938364/26159339/fba73d90-3ae3-11e7-9e1d-53dc30dd3e24.PNG)
[results.json](https://gist.github.com/Kujawadl/02d6cc029aecb68046ab444c0712264b)

**Comment by ostreifel** [comment]
So I was able to extract the data you were trying to render inject it into my browser as if I was getting the same results. What I saw:
![image](https://cloud.githubusercontent.com/assets/5203542/26165052/8228b0c0-3ae3-11e7-9abc-5d6311ced8ff.png)

What I did
- Put a break point at  queryResults.js renderResult
- run the sample query
- at the break point assign result and workitems with the objects I constructed from the above results.json file


[workitems.json](https://gist.github.com/ostreifel/78c453579198b77266abe0a9c09d0644)
[result.json](https://gist.github.com/ostreifel/8c7b817b39d96c35aed22290610c7698)

- f8 continue


Not quite sure why it's failing for you or why the linktype is being caught as an error in the editor either
![image](https://cloud.githubusercontent.com/assets/5203542/26165633/89605274-3ae5-11e7-93cf-fce1f472f11b.png)

**Comment by ostreifel** [comment]
I wonder if this might an issue with react versions. Investigating.

**Comment by ostreifel** [comment]
Which version of tfs are you using?

**Comment by ostreifel** [comment]
Setting up a test box

**Comment by ostreifel** [comment]
Have a repro this seems to be an issue with link queries on older tfs versions. Given that tfs 15.3 uses React v0.14.3 and vsts uses React (with addons) v15.3.1 I suspect this is a react version conflict. I'll try to bundle the react into the extension itself instead of using the ones provided by the tfs server.

Edit: Updating the react version was not required. Pushing simple fix.

**Comment by ostreifel** [comment]
Please verify this is fixed for you as well

**Comment by Kujawadl** [comment]
Fixed! Thanks!
