### ISSUE TITLE
Azure Dev Ops User not able to save WIQL queries if they contain an asof parameter

### ISSUE THREAD

**Issue by gtrimis** [ostreifel/wiql-editor#61]
From the wiql editor, if I add asof ‘2022-11-22T23:00:00’ to the query, I can run it, but I cannot save it.

Hitting the save button does not do anything. The user does not see an error message. When I looked at the network traffic, there was an error thrown when the button was being clicked. See attachment.
![devOpsBug](https://user-images.githubusercontent.com/22084632/207922075-ec9e29de-ef6d-4455-915c-9cb94abdbf81.png)
![error2](https://user-images.githubusercontent.com/22084632/207922095-6b443ac7-d53a-4fcf-8bfe-733d36294f00.png)

**Comment by lzocateli** [comment]
Hi @ostreifel / @gtrimis / @mmanela / @cschleiden  
Is this project/DevOps Marketplace discontinued? 
There has been no update since 2021! I would like to approve this DevOps extension for use in the company, but without an update since 2021 I will not be able to.

**Comment by AHGambiSno** [comment]
+1 for @lzocateli.  I wont be able to get approval for this extension either if it isn't being actively maintained.
