### ISSUE TITLE
Repo maintenance

### ISSUE THREAD

**Issue by MonzT** [ostreifel/wiql-editor#62]
Hi there
I'd like to find out if this repo is being actively maintained? 
Would love to use it but I cannot get permission from my company to do so due to the lack of recent commits. 

Please Advise? 
@ostreifel @mmanela @cschleiden

**Comment by cristiteodorov** [comment]
Exactly in the same scenario - any update would be great.

**Comment by nellyk** [comment]
Hopefully you are still interested in this, it is now published here https://marketplace.visualstudio.com/items?itemName=ms-devlabs.wiql-editor

**Comment by cristiteodorov** [comment]
@nellyk Thanks, this is great!
