### ISSUE TITLE
Clicking links (almost) always results in unauthorized response

### ISSUE THREAD

**Issue by Kujawadl** [ostreifel/wiql-editor#8]
This issue is occurring on TFS 2015 Update 4 (on premises).

In the playground, I run a query, and I get a list of responses. When I click any of the links, I get the following error:

```
Ajax request failed with status: Unauthorized.
TFS.Core.Ajax.AjaxException: Ajax request failed with status: Unauthorized.
```

Refreshing and hard-refreshing do nothing. However, if I *middle click* the link, it works as expected.

The same thing happened just now when clicking the "Report an issue" link at the top of the page; I got a bunch of `Refused to load the stylesheet '...' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' assets-cdn.github.com".` errors. Middle clicking fixes this issue as well.

Putting the github issue aside (as I haven't investigated that at all):

I looked into the cookies on the pages that are giving the errors: EditThisCookie shows all the cookies one would expect, however, looking into the Network tab in Chrome Dev Tools shows that all the Ajax requests are being sent *without* any cookies.

Looking into the iframe the results are being served from, `window.document.location` is empty. I have a feeling this is the root of the issue; chrome is making ajax requests based on the cookies applicable to window.document.domain, and finding none,

I ran the `$("a.row").attr("target", "_parent");` in the console and re-tried clicking any of the work item links and they all worked as expected, however they no longer opened in new tabs.

Please let me know if I can provide any more information that would assist you. I may have time to look into the error myself in about three weeks if you don't have time before then. Thanks.

**Comment by ostreifel** [comment]
Does $("a").attr("rel","noreferrer") do anything? If not I may need to do the [event intercepting](https://github.com/ostreifel/Pull-Request-Search/blob/master/scripts/PullRequestsView.tsx#L36) that I do within the pull request search  extension where the navigation is handled by javascript.

**Comment by ostreifel** [comment]
I setup a 2015u4 box (version# 14.114.26403) and was unable to repro with the steps given above (tried with ie/edge/ff/chrome) so I cannot verify what fixes the issue here. Awaiting your response.

**Comment by Kujawadl** [comment]
`$("a").attr("rel","noreferrer")` doesn't do anything, the links already have that attribute set. Removing the attribute doesn't help either.

I tried it in Chrome and Firefox on two different machines, under two different user accounts. The only thing that fixes it is the middle click workaround.

**Comment by ostreifel** [comment]
Please confirm 1.7.24 fixes the issue for you

**Comment by ostreifel** [comment]
Please confirm 1.7.29 fixes the issue for you

**Comment by Kujawadl** [comment]
1.7.29 fixes the issue. Thanks for the quick response!
