### ISSUE TITLE
Possible to set which TFS group can see this extension?

### ISSUE THREAD

**Issue by FredConklin** [ostreifel/wiql-editor#9]
This may be more of a question about TFS Extensions than about this particular extension.  Is it possible to restrict viewing of this extension to a particular group of TFS users? 
Thanks!

**Comment by ostreifel** [comment]
The closest secure way I that I can seem to find is to make a paid version of the extension and then to assign licences to the users that should be authorized. https://www.visualstudio.com/en-us/docs/marketplace/get-vsts-extensions#assign-paid-extension-access-to-users
